### ISSUE TITLE
Window Remains Black and Closes After a Few Seconds

### ISSUE THREAD

**Issue by RadzPrower** [teamsalta/sm64nx#2]
I managed to get the build.bat file to generate !!base.pak and run make without any apparent errors, but it just won't run as-is.

Windows 10

**Comment by Patjwmiller** [comment]
Make sure the romfs folder + SDL2.dll + baserom.z64(or whatever you named your rom) are in the same dir as the mario executable.

**Comment by RadzPrower** [comment]
Despite that not being conveyed as required in the practically non-existent installation instructions, I already tried that.

**Comment by ajohns6** [comment]
Despite that not being conveyed as required in the practically non-existent installation instructions, I already tried that.

**Comment by Patjwmiller** [comment]
You are right with this not being in the instruction. It's evident in the source. I skimmed the source to find this knowledge ;). However I don't know why it's still crashing for you. How are you building it?

**Comment by RadzPrower** [comment]
Compiled all the dependencies as best I could (I hate Python...), utilized the build.bat in import to create a !!base.pak (which I've compared file size with others and they say it matches), and I run "make -j64" (I picked 64 for the obvious reason, but it also seems to perform surprising well at that level with all the other ports as well).

**Comment by teamsalta** [comment]
is !!base.pak 3.5MB?

**Comment by RadzPrower** [comment]
Yes, I never got it running quite right myself, but now that the executable is included, it's running. I was able to run build.bat via cmd.exe instead.
